Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/yakkety64"
  config.vm.hostname = "nodo1"
  config.vm.provision "shell" do |s|
    s.path = "scripts/base.sh"
    s.env  = {
      "CONFIG_DIR" => "/vagrant/config"
    }
    config.vm.network "private_network", ip: "192.168.50.3"
  end
end
